use tauri_plugin_sql::{Migration, MigrationKind};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations(
                    "sqlite:typing_trainer.db",
                    // Versioned SQL migrations generated by drizzle-kit
                    // (`pnpm db:generate`) from `src/lib/db/schema.ts`.
                    // Applied once per DB version by tauri-plugin-sql at
                    // startup — idempotent by construction.
                    vec![
                        Migration {
                            version: 1,
                            description: "create_initial_schema".into(),
                            sql: include_str!("../migrations/0000_previous_pestilence.sql").into(),
                            kind: MigrationKind::Up,
                        },
                        // Phase 4: per-attempt key spotlight column on
                        // `lesson_attempts` (Results screen key cards).
                        Migration {
                            version: 2,
                            description: "attempt_key_report".into(),
                            sql: include_str!("../migrations/0001_gorgeous_ben_grimm.sql").into(),
                            kind: MigrationKind::Up,
                        },
                    ],
                )
                .build(),
        )
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
