use tauri_plugin_sql::{Migration, MigrationKind};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        // Phase 7 (§17): file pickers + scoped fs for JSON import/export.
        // Picking a file through the dialog plugin extends the fs scope to
        // exactly that path — no static broad grants (§5 offline rule).
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(
            tauri_plugin_sql::Builder::default()
                .add_migrations(
                    "sqlite:typing_trainer.db",
                    // Versioned SQL migrations generated by drizzle-kit
                    // (`pnpm db:generate`) from `src/lib/db/schema.ts`.
                    // Applied once per DB version by tauri-plugin-sql at
                    // startup — idempotent by construction.
                    vec![
                        Migration {
                            version: 1,
                            description: "create_initial_schema".into(),
                            sql: include_str!("../migrations/0000_previous_pestilence.sql").into(),
                            kind: MigrationKind::Up,
                        },
                        // Phase 4: per-attempt key spotlight column on
                        // `lesson_attempts` (Results screen key cards).
                        Migration {
                            version: 2,
                            description: "attempt_key_report".into(),
                            sql: include_str!("../migrations/0001_gorgeous_ben_grimm.sql").into(),
                            kind: MigrationKind::Up,
                        },
                        // Phase 6: intelligence features — bigram_statistics +
                        // key_statistics_daily rollups; lesson_attempts gains
                        // `kind` and a nullable lesson_id (drill attempts).
                        Migration {
                            version: 3,
                            description: "intelligence_rollups".into(),
                            sql: include_str!("../migrations/0002_tidy_liz_osborn.sql").into(),
                            kind: MigrationKind::Up,
                        },
                        // Phase 7: custom-lesson draft lifecycle + §17 import
                        // provenance (is_draft, source, collection_id,
                        // syntax_family, tags on `custom_lessons`).
                        Migration {
                            version: 4,
                            description: "custom_lesson_lifecycle".into(),
                            sql: include_str!("../migrations/0003_omniscient_ben_grimm.sql").into(),
                            kind: MigrationKind::Up,
                        },
                    ],
                )
                .build(),
        )
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
